# Generated by Django 6.0.3 on 2026-03-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('tag_rfid', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='TAG RFID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
