# Generated by Django 6.0.3 on 2026-03-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Equipamento')),
                ('cod_id', models.CharField(max_length=50, unique=True, verbose_name='Código de Barras / ID')),
                ('status', models.CharField(choices=[('ESTOQUE', 'Disponível em Estoque'), ('USO', 'Em uso / Retirado'), ('MANUTENÇÃO', 'Em Manutenção')], default='ESTOQUE', max_length=50)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
    ]
