# Generated by Django 6.0.3 on 2026-03-30 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.ativo', verbose_name='Equipamento')),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almoxarifado.colaborador', verbose_name='Responsável')),
            ],
        ),
    ]
